/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Robot by Poly by Google [CC-BY] (https://creativecommons.org/licenses/by/3.0/) via Poly Pizza (https://poly.pizza/m/9A6cuitiB_4)
*/

import * as THREE from "three";
import { OrbitControls, Environment, Sphere, useGLTF } from "@react-three/drei";

function Scene({ path, ...props }) {
  const { nodes, materials, scene } = useGLTF(path);

  return (
    <group {...props} dispose={null}>
      <OrbitControls
        autoRotate
        enablePan={false}
        minDistance={6}
        maxDistance={10}
        autoRotateSpeed={2}
      />
      <primitive
        object={scene}
        position={[0, -1, 0]}
        scale={[0.02, 0.02, 0.02]}
        rotation-y={-Math.PI / 2}
      />
      <Environment background>
        <Sphere scale={2}>
          <meshBasicMaterial color="hotpink" side={THREE.BackSide} />
        </Sphere>
      </Environment>
    </group>
  );
}

export default Scene;

useGLTF.preload("/models/Robot.glb");
